\\section{Working experience}

$working_experience:tex_experience()$

\\section{Professional experience}

$experience:tex_experience()$

\\personal[iceboal.com]{157 W 106th St Apt 3D}{New York, NY 10025}{+1 (347) 821-1086}{iceboal@gmail.com}

\\section{Education}

\\begin{yearlist}

$education:tex_education()$

\\end{yearlist}

\\section{Contest}

\\begin{yearlist}

$contest:tex_contest()$

\\end{yearlist}

\\section{Scholarships}

\\begin{yearlist}

$scholarships:tex_scholarships()$

\\end{yearlist}


\\section{Publications}

$publications: tex_publications()$

\\section{Skills}

\\begin{factlist}

$skills:tex_skills()$

\\end{factlist}




