\\section{Education}
\\begin{yearlist}
$education:tex_education()$
\\end{yearlist}

\\section{Work experience}

$working_experience:tex_experience()$

\\section{Academic experience}

$experience:tex_experience()$

\\subsection{Other Representative projects}

$projects:tex_projects()$

\\section{Contest and awards}

\\begin{yearlist}

$contest:tex_contest()$

\\end{yearlist}

\\section{Scholarships}

\\begin{yearlist}

$scholarships:tex_scholarships()$

\\end{yearlist}

\\section{Publications}

$publications: tex_publications()$

\\section{Skills}

\\begin{factlist}

$skills:tex_skills()$

\\end{factlist}




